### ISSUE TITLE
whalebone_client_id unhelpful message

### ISSUE THREAD

**Issue by hugeox** [whalebone/public-api#18]
When header param whalebone_client_id is either not set, or is set to an invalid value, i.e. a string, the message is : `{"error":"UNEXPECTED_ERROR","error_code":10,"message":"Unexpected error occurred (ref: something). Please note the \u0027ref\u0027 number and time and contact the administrator"}`

**Comment by kozeltom** [comment]
that's ok for now. The way how clientId is passed to api is not clarified yet, so this header param is just for testing purposes.
